SCA implementation
ampeco/omnipay-stripe pull request #1
Opened 2022-07-07 07:12 UTC by valentinDamyanovAmpeco

upd: purchase request with automatic confirmation so we can use confirmPayment in the stripe-react-native, add helper response methods to detect if authorization required.

upd: handle sea rest response.

add: handle payment_intent.payment_failed IPN 

fix: remove unnecessary code line

2022-07-07 14:01 UTC, dmtar requested changes

2022-07-07 14:01 UTC, dmtar commented on src/Message/NotificationResponse.php
> +class NotificationResponse extends Response
I'm not sure we are using this anywhere, but it seems more correct naming than RestResponse if it's just used for notification response

2022-07-07 14:01 UTC, dmtar commented on src/Message/PurchaseRequest.php
> +        $data['confirmation_method'] = 'automatic';
confirmation_method is relevant only for payment intents, the old charges API is not used at all. We only use the new payment intents API - PaymentIntentsGateway

2022-07-07 14:01 UTC, dmtar commented on src/Message/RestResponse.php
> +class RestResponse extends AbstractResponse
Directly extend the Response and override only the isSuccessful, getTransactionReference is already implemented there

2022-07-08 14:08 UTC, valentinDamyanovAmpeco commented on src/Message/RestResponse.php
> +class RestResponse extends AbstractResponse
our method `getTransactionReference` handles  `$this->data['data']['object']['charges']['data'][0]['id'] ?? null;`
while inherited have different usage

2022-07-14 12:15 UTC, merged